
include: package:flutter_lints/flutter.yaml

linter:

  rules:
    - camel_case_types
    - empty_catches
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - use_rethrow_when_possible
    - avoid_web_libraries_in_flutter
    - non_constant_identifier_names
    - unrelated_type_equality_checks
    - unnecessary_brace_in_string_interps
    - unnecessary_new
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - cascade_invocations
    - curly_braces_in_flow_control_structures
    - empty_constructor_bodies
    - empty_statements
    - file_names
    - flutter_style_todos
    - prefer_collection_literals
    - prefer_const_declarations
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_spread_collections
    - require_trailing_commas
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - use_function_type_syntax_for_parameters
    - use_full_hex_values_for_flutter_colors
    - use_string_buffers
