// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNmAtMd0Q4GkZ9K-RzJ5eNS4dJo6DsT-M',
    appId: '1:31723987810:web:1c9c0b214cfcf78d28823b',
    messagingSenderId: '31723987810',
    projectId: 'todolist-ecf92',
    authDomain: 'todolist-ecf92.firebaseapp.com',
    storageBucket: 'todolist-ecf92.appspot.com',
    measurementId: 'G-7WC7RVPNT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIAY-Ffhb57lzqWfVO1c3hifk6q0TQV_U',
    appId: '1:31723987810:android:60e19fe51655d3b428823b',
    messagingSenderId: '31723987810',
    projectId: 'todolist-ecf92',
    storageBucket: 'todolist-ecf92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdPSYGA8zRdyCMrGt6NHBQ75k7FrZAcV4',
    appId: '1:31723987810:ios:b3415d7e5894251328823b',
    messagingSenderId: '31723987810',
    projectId: 'todolist-ecf92',
    storageBucket: 'todolist-ecf92.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdPSYGA8zRdyCMrGt6NHBQ75k7FrZAcV4',
    appId: '1:31723987810:ios:b3415d7e5894251328823b',
    messagingSenderId: '31723987810',
    projectId: 'todolist-ecf92',
    storageBucket: 'todolist-ecf92.appspot.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNmAtMd0Q4GkZ9K-RzJ5eNS4dJo6DsT-M',
    appId: '1:31723987810:web:d76fd1e45a23282828823b',
    messagingSenderId: '31723987810',
    projectId: 'todolist-ecf92',
    authDomain: 'todolist-ecf92.firebaseapp.com',
    storageBucket: 'todolist-ecf92.appspot.com',
    measurementId: 'G-20D3LYL7F9',
  );
}
